### ISSUE TITLE
use of import or require allowed?

### ISSUE THREAD

**Issue by mandolyte** [elias-sundqvist/obsidian-react-components#14] opened 2021-06-01 15:48 UTC
A bit of testing shows that the import statement doesn't work since it must be top level and the code file is being wrapped.

Wondered if there was a way to use existing components from NPM inside the code bits?

Thoughts?

**Comment by elias-sundqvist** [comment] 2021-06-08 19:11
What works:
* If you define a component in one file, it can be used in another (no import needed)
* You can use `require` on the built-in obsidian packages.  (such as`electron`, `url`, and `path`. These may not work on mobile though.)

I agree that being able to add packages from npm would be useful, but it's a bit tricky to implement. 

If the package is pure javascript, it should be possible to load it by adding a `<script>` tag. I haven't experimented with this myself yet though. 

If there is a specific package you want to see added, you can make an issue and I can add it to the scope. 
This is not an ideal solution though... I'll try to think of a better solution next week when my exams are over.

**Comment by elias-sundqvist** [comment] 2021-06-13 15:43
Ok, I have now managed to come up with a solution for importing modules from the web (with skypack).
Here is an example:
![obsidian react components imports](https://user-images.githubusercontent.com/9102856/121813903-8123ad80-cc6e-11eb-8c65-b8c77faf51a6.gif)

The code is available in the dev branch.

**Comment by mandolyte** [comment] 2021-06-14 11:13
Super! I'll give it try with one of our material-ui components on NPM.

Hmmm, how do I use the dev branch? I've never written a plugin before, so I may have to rope in a colleague to try this out.

**Comment by elias-sundqvist** [comment] 2021-06-15 17:30
I just need to check that everything is stable and works as intended before adding these changes to a new release. 
It should take less than a week, so if you can wait until then that's probably the easiest option.

**Comment by elias-sundqvist** [comment] 2021-06-19 12:25
0.0.6 has now been released with support for URL imports. :)

**Closed** 2021-06-19 12:35 UTC
